// Package Openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"

	"github.com/GrivIN/CommonCodesApi/Openapi"
)

//
// OUR CODE
//

type ServerImpl struct{}

func (*ServerImpl) GetSystem(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte(fmt.Sprintf("title:%s", "XXX")))
	// Implement me
}

func (*ServerImpl) GetSystemSystemNameCodeCodeId(w http.ResponseWriter, r *http.Request, systemName string, codeId string) {
	// Implement me
}

func main() {
	var myServer ServerImpl
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	Openapi.HandlerFromMux(&myServer, r)
	http.ListenAndServe(":3333", r)
}
