// Package Openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package Openapi

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /system)
	GetSystem(w http.ResponseWriter, r *http.Request)

	// (GET /system/{systemName}/code/{codeId})
	GetSystemSystemNameCodeCodeId(w http.ResponseWriter, r *http.Request, systemName string, codeId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSystemSystemNameCodeCodeId operation middleware
func (siw *ServerInterfaceWrapper) GetSystemSystemNameCodeCodeId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "systemName" -------------
	var systemName string

	err = runtime.BindStyledParameter("simple", false, "systemName", chi.URLParam(r, "systemName"), &systemName)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter systemName: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "codeId" -------------
	var codeId string

	err = runtime.BindStyledParameter("simple", false, "codeId", chi.URLParam(r, "codeId"), &codeId)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter codeId: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystemSystemNameCodeCodeId(w, r, systemName, codeId)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system", wrapper.GetSystem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/system/{systemName}/code/{codeId}", wrapper.GetSystemSystemNameCodeCodeId)
	})

	return r
}
